name: Run code checks

on:
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "prs"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint && yarn lint:css
      - name: Test
        run: yarn test --passWithNoTests
      - name: Build
        run: yarn build
